### ISSUE TITLE
Wrong solution for #first_wa

### ISSUE THREAD

**Issue by lukegrecki** [learn-co-curriculum/collections_practice_vol_2#11]
The solution given also returns words with a "wa" anywhere in the string. Here's my solution:

``` ruby
def first_wa(array)
  array.find { |word| word[0..1] == "wa"}
end
```

This solution only matches "wa" at the start of the string.

**Comment by HuydDo** [comment]
def first_wa(array)
	wa_arr = []
	array.each do |item|
		if item[0..1] == ("wa")
			wa_arr << item
		end
	end
	# wa_arr[0]
	wa_arr.first
end

**Comment by maxwellbenton** [comment]
Hi @lukegrecki,

Thank you for spotting this and opening an issue. We've updated this lesson and incorporated changes based on you feedback, updating the tests and solution so that they align with the test message. The previous solution will no longer work, but your example solution still will.

Thank you for contributing to a Learn lesson!
