### ISSUE TITLE
count_elements test description is wrong

### ISSUE THREAD

**Issue by GuttermanA** [learn-co-curriculum/collections_practice_vol_2#17]
The test text is: count how many times something appears in an array

The test is actually on count how many times a value appears in a hash.

**Comment by maxwellbenton** [comment]
Hi @GuttermanA,

Thank you for opening this issue and providing feedback. We've updated this lesson's tests and changed the wording on this test so that it more accurately describes what is being expected. We've also added instructions and examples in the readme to help prevent confusion for future students, which should prevent this issue from occuring in the future.

Thank you for contributing to this lesson!
